### PR TITLE
Feature/parallel test agent

### PR DESCRIPTION
**Pull request by cpnota**
Follow up on #239 . Added `ParallelPreset.parallel_test_agent()` and modified `ParallelEnvExperiment.test()` to use the test `ParallelAgent`. Additional background can be found in Issue #220 .

### CODE REVIEW

**Comment by weepingwillowben** [comment]
Tested with 12 atari environments with a single threaded vector environment, got 3x faster FPS than 1 environment with PPO
With a multiprocessing vector environment with 12 environments, got 6x faster FPS. 

So there is substantial improvement with multiprocessing. So that is promising. 

I am running a bunch of examples manually to check that something wasn't missed.

**Comment by cpnota** [comment]
Nice, thanks!

**Comment by weepingwillowben** [comment]
So I don't think it is actually caused by this PR, but it is related.

```
import gym
import supersuit
from all.environments import GymVectorEnvironment, GymEnvironment, DuplicateEnvironment, AtariEnvironment
from all.presets.continuous import ppo
from all.presets.atari import a2c, vqn, ppo
from all.experiments import ParallelEnvExperiment

n_envs = 1
vec_env = DuplicateEnvironment([AtariEnvironment("SpaceInvaders", device="cuda") for i in range(n_envs)], device="cuda")
preset = vqn.env(vec_env).device("cuda").hyperparameters(n_envs=vec_env.num_envs).build()
experiment = ParallelEnvExperiment(preset, vec_env)
experiment.train(episodes=2)
```

The `n_envs=1` causes an error. Greater than 1 envs works fine.  I can't seem to track down the issue.

**Review by weepingwillowben — APPROVED** [review]
Other than the failing case, it looks really good. I don't see any problems.

**Comment by cpnota** [comment]
I'll look into the failing `n_envs=1` case.

**Pull request merged**
