### PR TITLE
Feature/state tensor

### PR DESCRIPTION
**Pull request by cpnota**
This is a major breaking update, new documentation will be need.

The first breaking change is that the `Agent` API has changed slightly. Instead of `act(state, reward)`, the function is now just `act(state)`:

```python
class Agent(ABC, Schedulable):
    @abstractmethod
    def act(self, state):
        pass

    @abstractmethod
    def eval(self, state):
        pass
```

What?! Don't we need reward?! The answer is that `reward` has been moved into `State`. The reason is that in many cases, we would have to separately concatenate rewards and states. This is kind of silly, and it is easier to just store them as a single object which performs these sorts of manipulators for us.

Also, `State` was *heavily* refactored. Previously, every `State` included an implicit `batch` dimensions. This was a bit awkward, so to fix that, there are now *two* objects, `State` and `StateTensor`. The `State` object is not vectorized: the observation is whatever the native shape of the observation is (e.g., `(4,)` for `CartPole`), `state.reward` is a float, `state.mask` is a float, and `state.done` is a bool. This is much faster at runtime than constructing tensors for each of these values.

On the other hand, the `StateTensor` object vectorizes all of these inputs. Unlike the old `State` object, which effectively only allowed one `batch` dimensions (e.g., `mask` was always a 1d tensor), `StateTensor` allows for more flexible shapes. For instance, it can represent parallel rollouts of batch size `b` and length `n` by storing tensors of shape `(b, n)`. The observation shape would be `(b, n, *observation_shape)`, where `observation_shape` is the native shape of the observation. `StateTensor` maintains this in a flexible way and allows for proper indexing.

Finally, both `State` and `StateTensor` now allow for arbitrary *additional* entries. For example, one could set `state['last_action'] = action` in order to use `state` as an input for a network. This allows for networks to respond to various inputs without needing to contrive the input into a single tensor, as would be necessary previously.

Also, `state.features` was renamed to `state.observation`.

There will probably be several follow-up pull requests in order to further improve functionality, performance, and to fix any bugs. There are some modules which I would like to refactor (```all.memory```, I'm looking at you...) I'm hoping these changes will make it also make it easier to implement some new agents!

### CODE REVIEW

**Comment by mctigger** [comment]
Hi @cpnota,
great update!

For what it's worth I want to comment on the naming. I think State should maybe called something different (although I am not sure what it should be called). To best understand the code in my opinion it should be as close as possible to the classical naming scheme in reinforcement learning. E.g. a POMDP has states, observations, actions and rewards. The State class does not really represent the states in an MDP. Rather, it represents the all the information that we get from a single environment step. Especially in model-based RL where we may infer the real state given an observation, the current naming may cause confusion between the state from an MDP and the state of the autonomous-learning-library.
A similar remark regarding the StateTensor. I think it would be natural to call it something like BatchedStates since the State class also contains tensors, just not in a batched way.

**Comment by cpnota** [comment]
Thanks!

Hm, I hear you're point, but I'm not totally sure what a better name would be. The entire thing could be called `Observation`, which might be more semantically correct, but what that just lead to more confusion? I just went with `State` for simplicity.

What I was trying to get across with `StateTensor` is that the object represents a tensor where each of the elements is a `State` (so it's not necessarily a mathematical `Tensor`). It's sort of similar to `NamedTensor` except that not all of the dimensions are the same shape. I'm not sure if there's a more appropriate mathematical name for this, maybe some kind of `Bundle`? Something like `StateBatch` maybe could work? I'll think about it!

**Comment by mctigger** [comment]
I agree, naming seems to be quite hard in this case. Maybe something like `Step` since it represents all the information that one step of the environment generates? This may be confusing on first read, but should clear things up once one sees the contents (this would also allow to maybe add a `.state` and a `.observation` attribute, which could be used for something like logging. However, I am not sure that is really a use-case.

Regarding the state tensor I think `StateBatch` is a good idea, but I have to take another look at code first to really understand what functionality you are intending to put into it.

**Comment by cpnota** [comment]
Having some Travis CI issues... going to merge to `develop` for now so that development can continue.

**Pull request merged**
