### PR TITLE
Ben/multi agent additions

### PR DESCRIPTION
**Pull request by weepingwillowben**
This is a PR to the multi-agent atari branch. In addition to minor fixes it has 2 major features:

1. A Parameter sharing wrapper. This is implemented via a hack: it just uses an independent agent with shallow copies of a single agent (copying through any bodies that wrap the agent). A shallow copy means that the prior state and action are not shared between agents, but the replay buffer and networks are.
2. A general pettingzoo env 
3. Various fixes of the multi-agent experiment class

### CODE REVIEW

**Comment by weepingwillowben** [comment]
I would be willing to split the parameter sharing wrapper into its own PR if you want

**Comment by cpnota** [comment]
This stuff looks good, though the parameter sharing stuff is a bit hacky.

I'm going to try to merge the multi-agent-atari branch first because I have close to full test coverage on it, then we can work on this one? Just need to get the setup.py and integration tests finished on the other branch.

**Comment by weepingwillowben** [comment]
Ok, I'll remove parameter sharing from this and put it into its own PR.

**Comment by weepingwillowben** [comment]
As far as I can tell, the options to implement parameter sharing based off existing agents are:

* Multi-agent presets which give out agents with the same replay buffers and optimizers (similar to what @cpnota had in the parameter sharing DQN implementation)
* A shallow copy of the agents (either through a hack like the current PR or through a .copy() method the agents have)

**Comment by weepingwillowben** [comment]
Ok, I removed the parameter sharing wrapper

**Pull request closed without merging**
