### PR TITLE
Add all current versions of Python to CI

### PR DESCRIPTION
**Pull request by justinkterry**
Adds 3.6-3.8 to CI. Testing this locally is hard, so when this inevitably fails I'll add fixes. Travis doesn't support 3.8.

### CODE REVIEW

**Comment by justinkterry** [comment]
@cpnota hey do you know why the tests aren't running? Me and Ben aren't sure

**Comment by cpnota** [comment]
TravisCI says the request was rejected due to "Could not parse". Looking [here](https://docs.travis-ci.com/user/languages/python/), looks like you can just add python versions like:

```yaml
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
  - master
  - develop
install:
  - pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install -q -e .["dev"]
script:
  - make lint
  - make test
```

**Review by cpnota — APPROVED** [review]
Looks like there are problems installing Box2D on 3.8, *sigh*

**Comment by justinkterry** [comment]
It's not box2d-py itself (which isn't regular box2d by the way, it's OpenAIs fork for Gym). We depend on that for PettingZoo, and Gym depends on it, and both are super heavily tested, including for 3.8.

I frankly have no clue what the problem is at the moment.

**Comment by cpnota** [comment]
Right, it looks like it's some conflict in the version of numpy required by box2d and something else. I will see if I can reproduce it in a little while.

**Pull request merged**
